name: Release Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  installing:
    name: Running Release Workflow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Running install ...
        run: yarn

      - name: Running linters ...
        run: yarn lint

      - name: Running tests ...
        run: yarn test
